name: "Cron Requester"
services:
  cron-requester:
    image: codedefective/cron-requester:latest
    build: .
    hostname: cron-requester
    container_name: cron-requester
    restart: unless-stopped
    volumes:
      - ./crons/jobs.txt:/crons/jobs.cron:ro
